export const defaultSettings = [
	{
		key: "APP_NAME",
		value: "RAG Platform",
		category: "general",
		description: "Name of the application displayed in the frontend",
	},
	{
		key: "THEME_COLOR",
		value: "#2563eb",
		category: "appearance",
		description: "Primary color for the UI",
	},
	{
		key: "APP_LOGO_URL",
		value: "https://cdn-icons-png.flaticon.com/512/188/188109.png",
		category: "appearance",
		description: "URL of the application logo",
	},
	{
		key: "DOC_CHUNK_SIZE",
		value: 1536,
		category: "processing",
		description: "Character size for document chunks",
	},
	{
		key: "DOC_CHUNK_OVERLAP",
		value: 256,
		category: "processing",
		description: "Character overlap between document chunks",
	},
	{
		key: "PST_CHUNK_SIZE",
		value: 1024,
		category: "processing",
		description: "Character size for email chunks",
	},
	{
		key: "PST_CHUNK_OVERLAP",
		value: 128,
		category: "processing",
		description: "Character overlap between email chunks",
	},
	{
		key: "SEARCH_LIMIT",
		value: 10,
		category: "search",
		description: "Default number of search results",
	},
	{
		key: "SEARCH_THRESHOLD",
		value: 0.6,
		category: "search",
		description: "Minimum similarity score for search results",
	},
	{
		key: "SMTP_HOST",
		value: "",
		category: "email",
		description: "SMTP Server Host",
	},
	{
		key: "SMTP_PORT",
		value: "587",
		category: "email",
		description: "SMTP Server Port",
	},
	{
		key: "SMTP_USER",
		value: "",
		category: "email",
		description: "SMTP Username",
	},
	{
		key: "SMTP_PASSWORD",
		value: "",
		category: "email",
		description: "SMTP Password",
	},
	{
		key: "SMTP_SECURE",
		value: "false",
		category: "email",
		description: "Use SSL/TLS for SMTP",
	},
	{
		key: "EMAIL_FROM",
		value: "noreply@example.com",
		category: "email",
		description: "Default sender email address",
	},
	{
		key: "JWT_EXPIRES_IN",
		value: "1d",
		category: "security",
		description: "JWT Token Expiry (e.g., 1h, 1d)",
	},
	{
		key: "MAX_FILE_SIZE_MB",
		value: 50,
		category: "processing",
		description: "Maximum file size for uploads in MB",
	},
	{
		key: "FRONTEND_URL",
		value: "http://localhost",
		category: "general",
		description: "Public URL of the frontend application",
	},
];
